# Generated by Django 4.2.15 on 2024-10-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_categorys_alter_category_slug_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
